version: '3.3'
services:
  sqldatabase:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /data/volume/dbpool/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example123
      - MYSQL_PASSWORD=example123
      - MYSQL_ROOT_HOST:'%'

  phpmyadmin_ui:
    container_name: phpmyadmin_container_ui
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: on-failure
    environment:
      PMA_HOST: sqldatabase
      PMA_USER: root
      PMA_PASSWORD: example123
    ports:
      - '0.0.0.0:8086:80'